/**
 * Compile-time proof that each namespace holds the same keys in both languages.
 *
 * Why this exists: `t()` returns the key itself when a lookup misses. A key
 * added to English and forgotten in Portuguese does not throw, does not warn
 * and does not fall back — it renders `notFoundTitle` on screen to every
 * Portuguese customer. Invisible in review, invisible in the build, which is
 * the combination that lets it ship.
 *
 * Both imports are `import type`, so this file is erased at compile time and
 * adds nothing to any bundle — in particular it does not pull the English
 * dictionaries into a chunk that only wanted the Portuguese ones.
 *
 * `verify:i18n` checks the same property at runtime, and more besides
 * (placeholder parity, empty strings, keys nothing uses). This file is the half
 * of it that fails during `pnpm typecheck`, in your editor, as you type.
 *
 * If you see a TypeScript error pointing here, do not edit this file. Read the
 * error: it names the offending keys. Add them to whichever dictionary lacks
 * them.
 */
import type commonEn from "./dictionaries/en/common";
import type commonPt from "./dictionaries/pt/common";
import type errorsEn from "./dictionaries/en/errors";
import type errorsPt from "./dictionaries/pt/errors";
import type navEn from "./dictionaries/en/nav";
import type navPt from "./dictionaries/pt/nav";
import type footerEn from "./dictionaries/en/footer";
import type footerPt from "./dictionaries/pt/footer";
import type homeEn from "./dictionaries/en/home";
import type homePt from "./dictionaries/pt/home";
import type authEn from "./dictionaries/en/auth";
import type authPt from "./dictionaries/pt/auth";
import type foodEn from "./dictionaries/en/food";
import type foodPt from "./dictionaries/pt/food";

/** Resolves only when `T` is `never`. When two dictionaries diverge, `T` is the
 *  union of the offending key names and the compiler prints them. */
type AssertNoStrayKeys<T extends never> = T;

type OnlyInFirst<A, B> = Exclude<keyof A, keyof B>;

export type CommonEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof commonEn, typeof commonPt>
>;
export type CommonPtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof commonPt, typeof commonEn>
>;

export type ErrorsEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof errorsEn, typeof errorsPt>
>;
export type ErrorsPtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof errorsPt, typeof errorsEn>
>;

export type NavEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof navEn, typeof navPt>
>;
export type NavPtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof navPt, typeof navEn>
>;

export type FooterEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof footerEn, typeof footerPt>
>;
export type FooterPtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof footerPt, typeof footerEn>
>;

export type HomeEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof homeEn, typeof homePt>
>;
export type HomePtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof homePt, typeof homeEn>
>;

export type AuthEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof authEn, typeof authPt>
>;
export type AuthPtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof authPt, typeof authEn>
>;

export type FoodEnHasNoKeysMissingFromPt = AssertNoStrayKeys<
  OnlyInFirst<typeof foodEn, typeof foodPt>
>;
export type FoodPtHasNoKeysMissingFromEn = AssertNoStrayKeys<
  OnlyInFirst<typeof foodPt, typeof foodEn>
>;
