import { FIREBASE_CONFIG, pushConfigured } from "@/services/push/config";

/**
 * `/firebase-messaging-sw.js` — the service worker that shows a notification
 * when no tab is in front (Phase 20g).
 *
 * **Why a route and not a file in `public/`.** Firebase's worker has to be
 * handed the project's config, and a static file cannot read the environment:
 * the old app solved that by pasting the keys into `public/firebase-messaging-
 * sw.js` and committing them, where they outlived two projects and a rotation.
 * Generated here, the worker is built from the same `FIREBASE_CONFIG` the page
 * uses, and a deployment with no push configured serves a worker that does
 * nothing rather than one that throws on every install.
 *
 * It must be served from the **root path** for its scope to cover the whole
 * site, which is what this route's position gives it.
 *
 * The worker is deliberately small and deliberately not bundled: `importScripts`
 * pulls Firebase's compat build, which is what a worker context can load.
 */
export const dynamic = "force-static";

const worker = (
  config: string,
) => `// Generated by app/firebase-messaging-sw.js/route.ts — do not edit by hand.
importScripts("https://www.gstatic.com/firebasejs/10.11.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/10.11.0/firebase-messaging-compat.js");

firebase.initializeApp(${config});
const messaging = firebase.messaging();

/** Where a notification leads. The locale prefix is left off on purpose: the
 *  proxy redirects an unprefixed path to the reader's own language, so the
 *  worker never has to guess which one a tab is in. */
function target(data) {
  const orderId = data && data.orderId;
  if (data && data.channelId === "order_notification" && orderId) {
    return "/account/orders/" + encodeURIComponent(orderId);
  }
  return "/notifications";
}

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const title = (payload.notification && payload.notification.title) || data.title;
  const body = (payload.notification && payload.notification.body) || data.body;

  // A tab that is open but not in front still updates its badges.
  self.clients
    .matchAll({ type: "window", includeUncontrolled: true })
    .then((clients) => {
      clients.forEach((client) => client.postMessage({ type: "deligo:push" }));
    })
    .catch(() => {});

  return self.registration.showNotification(title || "DeliGo", {
    body: body || "",
    icon: "/logo.svg",
    badge: "/logo.svg",
    // One notification per order replaces the last, rather than stacking five
    // of them for the same delivery.
    tag: data.orderId || "deligo",
    data: { url: target(data) },
  });
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || "/";
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((list) => {
      // An open tab is focused and navigated rather than a second one opened.
      for (const client of list) {
        if ("focus" in client) {
          if ("navigate" in client) client.navigate(url).catch(() => {});
          return client.focus();
        }
      }
      return clients.openWindow ? clients.openWindow(url) : undefined;
    }),
  );
});
`;

const EMPTY = `// Push is not configured for this deployment: no Firebase keys in the
// environment. A worker that does nothing is better than one that throws on
// every install.
self.addEventListener("install", () => self.skipWaiting());
`;

export async function GET(): Promise<Response> {
  const body = pushConfigured() ? worker(JSON.stringify(FIREBASE_CONFIG)) : EMPTY;
  return new Response(body, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The worker names its own scope by where it is served from; this says
      // so explicitly, so a move under a path would still cover the site.
      "Service-Worker-Allowed": "/",
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
